// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolarLab.BiddingService.Hosts.DbMigrator;

#nullable disable

namespace SolarLab.BiddingService.Hosts.DbMigrator.Migrations
{
    [DbContext(typeof(MigrationsAppDbContext))]
    [Migration("20260718114946_AddStartingPrice")]
    partial class AddStartingPrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolarLab.BiddingService.Domain.Contexts.Lots.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BidDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bid_date_time");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bids");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_bids_lot_id");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("SolarLab.BiddingService.Domain.Contexts.Lots.Entities.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("PlacementDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placement_date_time");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("starting_price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lots");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_lots_user_id");

                    b.ToTable("lots", (string)null);
                });

            modelBuilder.Entity("SolarLab.BiddingService.Domain.Contexts.Lots.Entities.Bid", b =>
                {
                    b.HasOne("SolarLab.BiddingService.Domain.Contexts.Lots.Entities.Lot", "Lot")
                        .WithMany("Bids")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bids_lots_lot_id");

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("SolarLab.BiddingService.Domain.Contexts.Lots.Entities.Lot", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
